name       : perl-error
version    : 0.17024
release    : 5
source     :
    - http://search.cpan.org/CPAN/authors/id/S/SH/SHLOMIF/Error-0.17024.tar.gz : 074db7c783a67b0667eca64a4f6a0c3de94998afc92c01d6453163eb04b9150d
license    :
    - Artistic-Perl-1.0
summary    : Perl error module
component  : programming.perl
builddeps  :
    - perl-module-build
description: |
    Error - Error/exception handling in an OO-ish way
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
