name       : perl-error
version    : '0.17026'
release    : 11
source     :
    - https://cpan.metacpan.org/authors/id/S/SH/SHLOMIF/Error-0.17026.tar.gz : 37590a962cd73ae03470e1ff16459a6cbc5273fc57626b8981dab9c2433155d9
license    :
    - Artistic-Perl-1.0
summary    : Perl error module
component  : programming.perl
builddeps  :
    - perl-module-build
description: |
    Error - Error/exception handling in an OO-ish way
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
