name       : perl-error
version    : '0.17029'
release    : 13
source     :
    - https://cpan.metacpan.org/authors/id/S/SH/SHLOMIF/Error-0.17029.tar.gz : 1a23f7913032aed6d4b68321373a3899ca66590f4727391a091ec19c95bf7adc
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Perl error module
builddeps  :
    - perl-module-build
description: |
    Error - Error/exception handling in an OO-ish way
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
