name       : perl-error
version    : 0.17025
release    : 7
source     :
    - https://cpan.metacpan.org/authors/id/S/SH/SHLOMIF/Error-0.17025.tar.gz : 6c9f474ad3d4fe0cabff6b6be532cb1dd348245986d4a6b600ad921d5cfdefaf
license    :
    - Artistic-Perl-1.0
summary    : Perl error module
component  : programming.perl
builddeps  :
    - perl-module-build
description: |
    Error - Error/exception handling in an OO-ish way
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
